### ISSUE TITLE
IAM for Sagemaker Notebook Instance Execution role (from template)  lack of access

### ISSUE THREAD

**Issue by racheliurui** [awslabs/predictive-maintenance-using-machine-learning#4]
While running the provided note book, I will get below exception,
```
Couldn't call 'describe_notebook_instance' to get the Role ARN of the instance PredictiveMaintenanceNotebookInstance.
```

It's related to the policy definition at below location,

https://github.com/awslabs/predictive-maintenance-using-machine-learning/blob/4f8135fd26688353f6fbe6fbd9da294bf9423de9/deployment/predictive-maintenance-using-machine-learning.template#L264-L270

After adding "sagemaker:DescribeNotebookInstance" access for above policy, the issue is fixed.

**Comment by vishaalkapoor** [comment]
Hi @racheliurui - thanks for the issue report. I'm having trouble reproducing the issue you have above. I've run the solution several times. Did you do anything additional in the solution to require the additional permissions - if so, I'd be interested as maybe we'd want to add the access role as a default? Thanks!

**Comment by racheliurui** [comment]
@vishaalkapoor  I didn't add extra solution , I do have some issue when provision the environment as the instance being referenced is under softlimit of my account, but other than that, I am just running through the solution.

**Comment by vishaalkapoor** [comment]
This is an unusual edge case where we are likely hitting a soft limit, which then requires DescribeNotebookInstance for special handling or an error message. We should add this access policy. What do you think @sojiadeshina?

**Comment by sojiadeshina** [comment]
Sorry for the delay. Sample IAM policy templates to launch and run the solution are included in the iam top level folder now. you add those policies to your account user in order to gain permissions to run everything in the solution: https://github.com/awslabs/predictive-maintenance-using-machine-learning/tree/master/iam
